service: disaster-alert-system-staging
frameworkVersion: '4'
provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: staging
  environment:
    EVENTS_TABLE: ${self:resources.Resources.EventsTable.Properties.TableName}
    ALERTS_TOPIC_ARN: { Ref: AlertsTopic }
    MET_API_KEY: ${env:MET_API_KEY, ''}
    MAPS_API_KEY: ${env:MAPS_API_KEY, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - { 'Fn::GetAtt': [ EventsTable, Arn ] }
        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
          Resource:
            - { Ref: AlertsTopic }
        - Effect: Allow
          Action:
            - comprehend:DetectEntities
          Resource: '*'
package:
  individually: true
functions:
  processTweet:
    handler: services/processing/dist/handlers/processTweet.handler
    events:
      - httpApi:
          method: POST
          path: /ingest/twitter
  getEvents:
    handler: services/processing/dist/handlers/getEvents.handler
    events:
      - httpApi:
          method: GET
          path: /events
  subscribe:
    handler: services/processing/dist/handlers/subscribe.handler
    events:
      - httpApi:
          method: POST
          path: /subscribe
resources:
  Resources:
    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: disaster-events-staging
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: verified
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: verified-index
            KeySchema:
              - AttributeName: verified
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    AlertsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: disaster-alerts-staging
